development:
  adapter: sqlite3
  database: /Users/ballen/Development/zackup/db/development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  adapter: sqlite3
  database: /Users/ballen/Development/zackup/db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: /Users/ballen/Development/zackup/db/production.sqlite3
  pool: 5
  timeout: 5000
