development:
  ip_address: 127.0.0.1
  hostname: localhost
  loop_interval: 30
  #Zvol Used to Store all Backups
  backup_zvol: rpool/backup
  time_zone: 'Eastern Time (US & Canada)'
  
test:
  ip_address: 127.0.0.1
  hostname: localhost

production:
  ip_address: 127.0.0.1
  hostname: localhost