development:
  ip_address: 127.0.0.1
  hostname: localhost
  loop_interval: 10
  #Mount Point of ZFS FS to Store all Backups
  backup_root: /backup
  
test:
  ip_address: 127.0.0.1
  hostname: localhost

production:
  ip_address: 127.0.0.1
  hostname: localhost